# Generated by Django 4.0.6 on 2022-07-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_bucketlist', '0005_remove_book_users_userbooklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbooklist',
            old_name='users',
            new_name='user',
        ),
    ]
