# Generated by Django 4.0.6 on 2022-07-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_bucketlist', '0006_rename_users_userbooklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(through='book_bucketlist.UserBookList', to='book_bucketlist.user'),
        ),
        migrations.RemoveField(
            model_name='userbooklist',
            name='book',
        ),
        migrations.AddField(
            model_name='userbooklist',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_bucketlist.book'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userbooklist',
            name='user',
        ),
        migrations.AddField(
            model_name='userbooklist',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='book_bucketlist.user'),
            preserve_default=False,
        ),
    ]
